site_name: BIDS Extension Proposals

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Guide: guide.md
  - Submission Process: submission.md
  - The Schema and Validator: 
      - About the Schema: schema.md
      - Parts of the Schema: how-the-schema-works.md
      - Schema Objects: schema_objects.md
      - Schema Rules: schema_rules.md
      - Schema Meta: schema_meta.md

theme:
    name: material
    favicon: assets/favicon/favicon.ico
    logo: assets/img/logo.png
    features:
      - navigation.sections

markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
